version: 2

project_name: k8ly
builds:
  - id: k8ly-cli
    main: ./main.go
    dir: ./cli
    binary: k8ly
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format_overrides:
      - goos: linux
        format: tar.gz
      - goos: darwin
        format: tar.gz
# archives:
#  - format: tar.gz
    #    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    #files:
      # - k8ly

release:
  github:
    owner: Omotolani98
    name: k8ly

ldflags:
  - "-s -w -X main.version={{ .Version }}"

changelog:
  sort: asc

