apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.name }}
