name: Build and Push Logly

on:
    push:
        branches: [dev]
    workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Nixpacks
        run: |
          curl -sSL https://nixpacks.com/install.sh | bash

      - name: Build Docker image with Nixpacks
        run: |
          cd services/logly
          nixpacks build . --name k8ly/logly --tag ${{ secrets.DOCKERHUB_USERNAME }}/logly:${{ github.sha }}
          nixpacks build . --name k8ly/logly --tag ${{ secrets.DOCKERHUB_USERNAME }}/logly:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/logly:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/logly:latest